progress bar add write interface
juicedata/juicefs pull request #1436
Opened 2022-02-16 13:21 UTC by zhijian-pro

Based on [mbp](github.com/vbauerster/mpb) v7.0.3 version code modification, add write interface to it, to achieve the effect that the progress bar and the log will not overlap each other

2022-02-16 13:29 UTC, zhijian-pro commented
**GC** 
<img width="2351" alt="image" src="https://user-images.githubusercontent.com/31313340/154274295-22c7128f-a868-4fb9-9ffb-d48a19229d6f.png">
**unit test**
<img width="2382" alt="image" src="https://user-images.githubusercontent.com/31313340/154274362-ae7cf26b-746a-41c6-9bfd-86873819009b.png">

2022-02-16 13:52 UTC, davies approved these changes

2022-02-16 14:30 UTC, SandyXSD commented on pkg/utils/progress.go
> +	SetOutput(os.Stderr, true)
It's possible to use progress bar in a mounted client, e.g: backup will call DumpMeta

2022-02-16 14:32 UTC, SandyXSD requested changes
need fix

2022-02-16 15:06 UTC, davies commented on pkg/utils/logger.go
> +		logger.tty = istty
tty is used by DisableLogColor(), we need to add `colorful` for that rather than using `tty=false`

2022-02-17 02:36 UTC, zhijian-pro commented
> 
stderr stdout is redirected to a file during mount
<img width="1742" alt="image" src="https://user-images.githubusercontent.com/31313340/154393789-0c177afb-65fc-422a-a4c9-c1e26e211f8d.png">

![image](https://user-images.githubusercontent.com/31313340/154393486-f2b361b1-31da-4a1d-9158-764b12a9469d.png)
Test backup meta when mount is ok
<img width="2098" alt="image" src="https://user-images.githubusercontent.com/31313340/154393424-5fe99803-024e-4b3e-9779-2460f6dcec84.png">

2022-02-17 02:52 UTC, davies commented on pkg/utils/logger.go
> +	colorful := isatty.IsTerminal(os.Stderr.Fd())
We should not change it.

2022-02-17 02:54 UTC, davies approved these changes

2022-02-17 03:03 UTC, SandyXSD approved these changes

2022-02-17 03:22 UTC, merged