doc: add oracle cloud object storage
juicedata/juicefs pull request #1533
Opened 2022-03-08 09:54 UTC by zhijian-pro

2022-03-08 09:56 UTC, zhijian-pro commented
#1516

2022-03-09 01:41 UTC, xiaogaozi requested changes

2022-03-09 01:41 UTC, xiaogaozi commented on docs/zh_cn/reference/how_to_setup_object_storage.md
> +    --access-key <API-key> \
这里的 instance ID 应该要换成 secret key？

2022-03-09 01:57 UTC, xiaogaozi approved these changes

2022-03-09 01:58 UTC, merged