docs: add colab tutorial
juicedata/juicefs pull request #1941
Opened 2022-04-29 07:29 UTC by liufuyang

Let's add a tutorial doc for using juicefs in Colab :)

2022-05-01 21:10 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +anybody to write and execute arbitrary python code through the browser, and is especially well suited to machine
```suggestion
anybody to write and execute Python code in the browser, and is especially well suited to machine
```

2022-05-01 21:10 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +Colab supports Google Drive for upload files to or download files from Colab instances. However, in some cases, Google
```suggestion
Colab supports Google Drive to upload files to or download files from Colab instances. However, in some cases, Google
```

2022-05-01 21:15 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +We illustrate the needed steps for using JuiceFS in Colab environment. We use Google CloudSQL as the JuiceFS metadata
```suggestion
The demo shows the steps that are needed to use JuiceFS in the Colab environment. We use Google CloudSQL as the JuiceFS metadata
```

2022-05-01 21:16 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +Many of the steps mentioned here will be quite similar with
```suggestion
Many of the steps mentioned here are quite similar with
```

2022-05-01 21:16 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +which you can also use for reference.
```suggestion
which you can also refer to.
```

2022-05-01 21:17 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +3. Happily storing sharing files cross machines and platforms
```suggestion
3. Happily storing sharing files across machines and platforms
```

2022-05-01 21:18 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +Otherwise, if you have another cloud vendors' resources (for example AWS's RDBS and S3), you can still use this guide as
```suggestion
Alternatively, if you have other cloud vendors' resources (for example AWS's RDBS and S3), you can still use this guide as
```

2022-05-01 21:18 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +You might also want the Colab instance is in the same zone or close to the region where CloudSQL and GCS are deployed,
```suggestion
You might also want the Colab instance to be in the same region or close to the region where CloudSQL and GCS are deployed,
```

2022-05-01 21:19 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +to make JuiceFS reaching the best performance. The tutorial should work for a random hosted Colab instance but you might
```suggestion
to make JuiceFS achieve the best performance. The tutorial should work for a random hosted Colab instance but you might
```

2022-05-01 21:20 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +* A Google Cloud Platform account ready and also a *porject* created. In our case we will use GCP project
```suggestion
* A Google Cloud Platform account ready and also a *project* created. In our case we will use the GCP project
```

2022-05-01 21:20 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +  as `juicefs-learning` for the demo
```suggestion
  named as `juicefs-learning` in the demo
```

2022-05-01 21:21 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +* A CloudSQL (Postgres) ready to be used. In this demo uses instance
```suggestion
* A CloudSQL (Postgres) ready to be used. This demo uses the instance
```

2022-05-01 21:22 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +This step is only need to be done once, and you can choose to do this at any machine/instance where you have good
```suggestion
This step only needs to be done once, and you can choose to do this at any machine/instance where you have good
```

2022-05-01 21:23 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +In this example I am doing this on my local machine. Firstly you can use
```suggestion
This demo shows an example conducted on a local machine. Firstly you can use
```

2022-05-01 21:25 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +`gcloud auth application-default login` to get a local credential ready or you can also
```suggestion
`gcloud auth application-default login` to get a local credential ready. When the option `application-default` is used, 
```

2022-05-01 21:26 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +use `GOOGLE_APPLICATION_CREDENTIALS` to setup as json key file.
```suggestion
the environment variable `GOOGLE_APPLICATION_CREDENTIALS` needs to be set up as a json key file.
```

I modify the text a bit based on what we have discussed.

2022-05-01 21:26 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +# Or set up the json key file via GOOGLE_APPLICATION_CREDENTIALS=/path/to/key
```suggestion
# and set up the json key file via GOOGLE_APPLICATION_CREDENTIALS=/path/to/key
```

2022-05-01 21:27 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +Then later we can mount this filesystem in any other machines/instances where you have access to your cloud resources.
```suggestion
Then later we can mount this file system in any other machines/instances where you have access to your cloud resources.
```

2022-05-01 21:28 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +You can download `juicefs` [here](https://github.com/juicedata/juicefs/releases).
```suggestion
`juicefs` can be downloaded [here](https://github.com/juicedata/juicefs/releases).
```

2022-05-01 21:31 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +    "postgres://postgres:mushroom1@localhost:5432/juicefs?sslmode=disable" \
```suggestion
    "postgres://postgres:mushroom1@localhost:5432/juicefs?sslmode=disable" \
    # juicefs on the above line is the name of the database created in the Google SQL instance juicefs-sql-example-1 
```
Add an annotation here to explain what `juicefs` means in line 92. Please check if it is correct.

2022-05-01 21:32 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +Noticing again, this step above is only need to be done once at any machine you feel like to work on.
```suggestion
Again, this step above only needs to be done once at any machine you like to work on.
```

2022-05-01 21:34 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +After you have finished with Step 1 above, then it means you already have a JuiceFS filesystem (called `myvolume` in
```suggestion
After you have successfully formatted the juicefs file system by following Step 1 above, you should have a JuiceFS filesystem named `myvolume` in
```

2022-05-01 21:34 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +this case) is defined and ready to be used.
```suggestion
ready to be used.
```

2022-05-01 21:35 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +So here we open a Colab page and run those command to mount our filesystem into a folder called `mnt`.
```suggestion
Then open a Colab page and run the following commands to mount our filesystem into a folder called `mnt`.
```

2022-05-01 21:36 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +Note that the follow commands are run in Colab environment so there is a
```suggestion
As the following commands are run in a Colab environment, an exclamation mark 
```

2022-05-01 21:37 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +`!` mark in the beginning for running shell command.
```suggestion
`!` is in the beginning for running shell command.
```

2022-05-01 21:39 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +
```suggestion
If the option `application-default` is used, the environment variable `GOOGLE_APPLICATION_CREDENTIALS` probably needs to be set up in your terminal.
```

2022-05-01 21:41 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +anytime in any other machines so to have access again to the data previously stored or to store more data into it.
```suggestion
anytime in any other machines to access the previously stored data or to store more data into it.
```

2022-05-01 21:42 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +Congratulations! Now you have learned how to use JuiceFS and specifically how to use it with Google Colab to
```suggestion
Congratulations! Now you have learned how to use JuiceFS with Google Colab to
```

2022-05-01 21:43 UTC, AIXjing commented on docs/en/tutorials/juicefs_on_colab.md
> +conveniently sharing and storing data files in a distributed fashion.
```suggestion
conveniently share and store data files in a distributed fashion.
```

2022-05-05 10:28 UTC, xiaogaozi requested changes

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +the [getting started doc](../getting-started/for_distributed.md)
```suggestion
the [getting started document](../getting-started/for_distributed.md)
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +## Summary of steps:
```suggestion
## Summary of steps
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +1. Format a `juicefs` file system from any machine/instance which having access to Google cloud resources
```suggestion
1. Format a JuiceFS file system from any machine/instance which having access to Google Cloud resources
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +2. Mount `juicefs` file system in a Colab Notebook
```suggestion
2. Mount JuiceFS file system in a Colab Notebook
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +## Prerequisite
```suggestion
## Prerequisites
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +In this demo we will use Google Cloud Platform's CloudSQL and Google Cloud Storage (GCS) as the backbone for creating a
```suggestion
In this demo we will use Google Cloud Platform's Cloud SQL and Google Cloud Storage (GCS) as the backbone for creating a
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +massive high performance file storage system via `juicefs`. It is required that you have a Google Cloud Platform account
```suggestion
massive high performance file storage system via JuiceFS. It is required that you have a Google Cloud Platform account
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +Otherwise, if you have another cloud vendors' resources (for example AWS's RDBS and S3), you can still use this guide as
```suggestion
Otherwise, if you have another cloud vendors' resources (for example Amazon RDS and S3), you can still use this guide as
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +a reference and with other reference docs provided by `juicefs` to achieve a similar solution.
```suggestion
a reference and with other reference documents provided by JuiceFS to achieve a similar solution.
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +You might also want the Colab instance is in the same zone or close to the region where CloudSQL and GCS are deployed,
```suggestion
You might also want the Colab instance is in the same zone or close to the region where Cloud SQL and GCS are deployed,
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +notice a slow performance due to the latency between the Colab instance and the CloudSQL/GCS regions. To start Colab
```suggestion
notice a slow performance due to the latency between the Colab instance and the Cloud SQL/GCS regions. To start Colab
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +.
```suggestion
see [instructions for starting a GCE VM on Colab via GCP Marketplace](https://research.google.com/colaboratory/marketplace.html).
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +* A CloudSQL (Postgres) ready to be used. In this demo uses instance
```suggestion
* A Cloud SQL (for MySQL or PostgreSQL) ready to be used. In this demo uses instance
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +  `juicefs-learning:europe-west1:juicefs-sql-example-1` as the metadata service
```suggestion
  `juicefs-learning:europe-west1:juicefs-sql-example-1` as the metadata engine
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +* An IAM ServiceAccount or an authrized user account that has write access to the posgtes server and GCS buckets
```suggestion
* An IAM Service Account or an authorized user account that has write access to the Cloud SQL service and GCS buckets
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +## Detailed Steps
```suggestion
## Detailed steps
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +### Step 1 - Format and mount a juicefs file system folder
```suggestion
### Step 1 - Format and mount JuiceFS file system
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +use `GOOGLE_APPLICATION_CREDENTIALS` to setup as json key file.
```suggestion
use `GOOGLE_APPLICATION_CREDENTIALS` to setup as JSON key file.
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +this case 5432) locally so to expose your cloud Postgres service to your local machine:
```suggestion
this case `5432`) locally so to expose your cloud PostgreSQL service to your local machine:
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +# Or set up the json key file via GOOGLE_APPLICATION_CREDENTIALS=/path/to/key
```suggestion
# Or set up the JSON key file via GOOGLE_APPLICATION_CREDENTIALS=/path/to/key
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +You can download `juicefs` [here](https://github.com/juicedata/juicefs/releases).
```suggestion
Please refer to the ["Installation & Upgrade"](../getting-started/installatioin.md) document to learn how to download JuiceFS.
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +### Step 2 - Mount juicefs file system on colab
```suggestion
### Step 2 - Mount JuiceFS file system on Colab
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +So here we open a Colab page and run those command to mount our filesystem into a folder called `mnt`.
```suggestion
So here we open a Colab page and run those command to mount our file system into a folder called `mnt`.
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +Firstly we download the `juicefs` binary and do the same as Step 1 to get GCP credentials and open cloudsql proxy.
```suggestion
Firstly we download the `juicefs` binary and do the same as Step 1 to get GCP credentials and open Cloud SQL proxy.
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +`!` mark in the beginning for running shell command.
```suggestion
:::note
The following commands are run in Colab environment so there is a `!` mark in the beginning for running shell command.
:::
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +1. Download `juicefs` to colab runtime instance
```suggestion
1. Download JuiceFS to Colab runtime instance
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +1. Set up Google Cloud credentials
```suggestion
2. Set up Google Cloud credentials
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +1. Open cloud_sql_proxy
```suggestion
3. Open `cloud_sql_proxy`
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +1. Mount JuiceFS filesystem `myvolumn` onto folder `mnt`
```suggestion
4. Mount JuiceFS file system `myvolumn` onto folder `mnt`
```

2022-05-05 10:28 UTC, xiaogaozi commented on docs/en/tutorials/juicefs_on_colab.md
> +Now you should be able to use the folder `mnt` as if it is a local filesystem folder to write and read folders and files
```suggestion
Now you should be able to use the folder `mnt` as if it is a local file system folder to write and read folders and files
```

2022-05-20 08:40 UTC, xiaogaozi commented
As concluded in a private discussion with @liufuyang, this PR will be merged first and then continue with changes in a new PR.

2022-05-20 08:41 UTC, merged