meta/tkv: reduce memory for loading into kv storage
juicedata/juicefs pull request #2142
Opened 2022-05-30 07:02 UTC by davies

Currently, we need to load all the entries into memory, then write them into kv storage one by one. This PR change it to load entries as a stream and write them into kv storage as batches.

For a volume with 10 millions of files, this PR reduce  the memory from 20G to 1G,  reduce  the time to load into badge from 12 minutes to 2 minutes.

2022-05-30 13:13 UTC, SandyXSD requested changes

2022-05-30 13:13 UTC, SandyXSD commented on pkg/meta/tkv.go
> +		_ = m.loadEntry(&e, cs, parents, refs, kv)
In this case, we use the attribute of the first link, not the newest one any more

2022-05-30 13:13 UTC, SandyXSD commented on pkg/meta/tkv.go
> +				binary.BigEndian.PutUint64(a[63:71], 0)
a[64:72] ?

2022-05-30 14:19 UTC, davies commented on pkg/meta/tkv.go
> +			_, err = m.decodeEntry(dec, 1, counters, parents, refs, kv, showProgress)
Why not 1?  the path is /.trash/

2022-05-30 14:27 UTC, davies commented on pkg/meta/tkv.go
> +				binary.BigEndian.PutUint64(a[63:71], 0)
no, there is 8 byte left

2022-05-31 02:35 UTC, SandyXSD approved these changes

2022-05-31 03:44 UTC, merged