improve FAQ doc
juicedata/juicefs pull request #2396
Opened 2022-07-25 03:58 UTC by zhijian-pro

- [x] zh

- [ ] en

2022-07-25 09:40 UTC, SandyXSD requested changes

2022-07-25 09:40 UTC, SandyXSD commented on docs/zh_cn/faq.md
> +通过 [JuiceFS 随机写的基本原理是什么](##JuiceFS 随机写的基本原理是什么) 这个问题的答案可以推断出，对象存储的占用空间大部分情况下是大于等于实际大小的，尤其是短时间内进行大量的覆盖写产生许多文件碎片后。这些碎片在未触发合并与回收前其仍旧占用着对象存储的空间。不过也不必担心这些碎片一直占用空间，因为在每次读文件的时候都会触发该文件相关碎片的整理工作。另外你可以通过 `juic
每次读的时候检查，并在必要的时候才触发

2022-07-25 09:40 UTC, SandyXSD commented on docs/zh_cn/faq.md
> +- Hadoop SDK： 方便在 Hadoop 体系中使用的 HDFS 接口[高度兼容](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/filesystem/introduction.html)的 Java 客户端。详情参考[在 Hadoop 中使用 JuiceFS](https://juice
多了空格。统一冒号

2022-07-25 09:40 UTC, SandyXSD commented on docs/zh_cn/faq.md
> +Linux 系统上日志文件默认是`/var/log/juicefs.log`
中英文间加空格
另外默认位置非 root 用户会不一样

2022-07-25 09:40 UTC, SandyXSD commented on docs/zh_cn/faq.md
> +到 JuiceFS 1.0.0-rc3 为止，还不支持该功能。
去掉 rc3 吧，1.0 为止都不会支持了

2022-07-25 09:40 UTC, SandyXSD commented on docs/zh_cn/faq.md
> +到 JuiceFS 1.0.0-rc3 为止，还不支持该功能。
Hadoop 对接的就是 Java SDK。另外有个 python 的 SDK，社区贡献但不一定成熟：
https://github.com/megvii-research/juicefs-python

2022-07-26 10:10 UTC, SandyXSD approved these changes

2022-07-26 11:30 UTC, xiaogaozi approved these changes

2022-07-26 11:33 UTC, merged