pkg/gateway: Support specifying umask for directories
juicedata/juicefs pull request #2445
Opened 2022-08-02 11:58 UTC by dugusword

Currently, gateway does not respect the umask flag specified in the start command, instead, it hard codes 755 for all the directories it creates. I have added an option, umask-dir, which will dictate the umask for all the mkdir calls. I keep them as separate flags in case some users would like their umasks different for folders and directories.

The following screenshots show different behaviors when gateway is started with umask-dir 022 vs 000.
![image](https://user-images.githubusercontent.com/6692644/182369216-da1bd06d-b7d7-4f03-9b8b-4dcfc684f9ac.png)

2022-08-02 11:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/juicedata/juicefs?pullRequest=2445) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/juicedata/juicefs?pullRequest=2445) before we can accept your contribution.<br/><hr/>**Biye Li** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/juicedata/juicefs?pullRequest=2445) it.</sub>

2022-08-09 08:51 UTC, davies commented
I think we should use the same umask for both file and dirs. When some user really need a separate umask, we can add that later.

2022-08-09 08:52 UTC, davies requested changes
use same umask for both file and directory

2022-08-09 09:46 UTC, dugusword commented
> I think we should use the same umask for both file and dirs. When some user really need a separate umask, we can add that later.

Cool. I can make the update. One question I do have is, though, I believe when using a shell, the base permission for file is 0666 while for directories it's 0777. Should we have the same behavior?

2022-08-09 12:24 UTC, davies approved these changes

2022-08-10 07:53 UTC, merged