CI:fix git clone err
juicedata/juicefs pull request #2736
Opened 2022-09-13 09:19 UTC by sanwan

2022-09-14 09:06 UTC, zhoucheng361 approved these changes

2022-09-14 12:56 UTC, davies commented on .github/actions/clickhouse/action.yml
> +        git clone https://github.com/sanwan/actionfile.git || git clone https://github.com/sanwan/chdata.git
actionfile

2022-09-15 16:28 UTC, davies requested changes
chdata  -> actionfile

2022-09-16 04:00 UTC, davies commented on .github/actions/clickhouse/action.yml
> +        git clone https://github.com/sanwan/chdata.git || git clone https://github.com/sanwan/chdata.git
When `git clone` fail in the middle, we need to remove the partial dir and try again.

2022-09-16 06:16 UTC, merged