cmd/fsck: support the nlink of the check and repair directory
juicedata/juicefs pull request #2785
Opened 2022-09-20 13:41 UTC by zhijian-pro

close #2772

2022-09-21 02:14 UTC, SandyXSD commented on cmd/fsck.go
> +				Name:  "recur",
use ` --recursive, -r`

2022-09-22 03:08 UTC, SandyXSD commented on pkg/meta/sql.go
> +		if ok, err := s.ForUpdate().Get(&node{Inode: inode}); err == nil && ok {
```suggestion
ok, err := s.ForUpdate().Get(&node{Inode: inode})
if err == nil {
    if ok {
	_, err = s.Update(n, &node{Inode: inode})
    } else {
	err = mustInsert(s, n)
    }
}
return err
```

2022-09-22 03:10 UTC, SandyXSD commented on pkg/meta/base_test.go
> +	testCheckAndRepair(t, m)
put it before setting `ReadOnly = true`?

2022-09-22 04:01 UTC, SandyXSD requested changes

2022-09-22 04:01 UTC, SandyXSD commented on pkg/meta/base.go
> +	if st = m.walk(ctx, inode, fpath, &attr, func(ctx Context, inode1 Ino, path string, attr *Attr, st1 syscall.Errno) syscall.Errno {
Can we do the check in parallel in recursive mode?

2022-09-22 12:47 UTC, davies commented on pkg/meta/redis.go
> +		err = tx.Set(ctx, m.inodeKey(inode), m.marshal(attr), 0).Err()
?

2022-09-22 12:48 UTC, zhijian-pro commented on pkg/meta/redis.go
> +		err = tx.Set(ctx, m.inodeKey(inode), m.marshal(attr), 0).Err()
sorry.

2022-09-23 11:28 UTC, merged