Add more logs and update log level in `disk_cache.go`
juicedata/juicefs pull request #371
Opened 2021-04-30 07:27 UTC by xiaogaozi

- Add cache directory path to every log of `cacheStore` to help distinguish different directory when use multiple cache directories
- Add log before execute `cacheStore.cleanup()` to know more context
- Upgrade some logs level (DEBUG → INFO, INFO → WARNING)

2021-04-30 07:37 UTC, Sandy4999 approved these changes

2021-05-04 01:38 UTC, davies commented on pkg/chunk/disk_cache.go
> +	logger.Infof("Scan %s to find cached blocks", cachePrefix)
We scan cached blocks in every 10 minutes, so it will be annoying.

2021-05-04 01:38 UTC, davies commented on pkg/chunk/disk_cache.go
> +	logger.Infof("Found %d cached blocks (%d bytes) in %s with %s", len(cache.keys), cache.used, cache.dir, time.Since(start))
We scan cached blocks in every 10 minutes, so it will be annoying.

2021-05-04 01:38 UTC, davies commented on pkg/chunk/disk_cache.go
> +		logger.Infof("cleanup cache (%s): %d blocks (%d MB), freed %d blocks (%d MB)", cache.dir, len(cache.keys), cache.used>>20, len(todel), freed>>20)
There will be many of this one, it's noisy

2021-05-04 01:39 UTC, davies commented on pkg/chunk/disk_cache.go
> +		logger.Infof("Cleanup cache when add new data (%s): %d blocks (%d MB), maximum %d blocks (%d MB)", cache.dir, len(cache.keys), cache.used>>20, cache.limit, cache.capacity>>20)
There will be many of this one, it's noisy

2021-05-04 01:42 UTC, davies commented on pkg/chunk/disk_cache.go
> +		logger.Infof("Caching queue is full (%s), drop %s (%d bytes)", cache.dir, key, len(p.Data))
it's OK to drop some blocks, or too noisy.

2021-05-04 01:42 UTC, davies commented on pkg/chunk/disk_cache.go
> +			logger.Infof("Cleanup cache when check free space (%s): free ratio (%d%%), space usage (%d%%), inodes usage (%d%%)", cache.dir, int(cache.freeRatio*100), int(br*100), int(fr*100))
too many

2021-05-04 01:43 UTC, davies commented on pkg/chunk/disk_cache.go
> +		logger.Warnf("Rename cache file %s -> %s failed: %s", tmp, path, err)
We may remove some directory concurrently, it's OK to fail.

2021-05-04 01:43 UTC, davies commented on pkg/chunk/disk_cache.go
> +		logger.Warnf("Can't create cache file %s: %s", tmp, err)
We may remove some directory concurrently, it's OK to fail.

2021-05-04 01:46 UTC, davies requested changes
For cache, it's normal to fail, or evict some of blocks, and we don't want to user to pay attention to these, otherwise it will be too noisy.

2021-05-06 03:17 UTC, davies approved these changes

2021-05-06 04:06 UTC, merged