docs: add dump/load commands
juicedata/juicefs pull request #521
Opened 2021-06-16 06:03 UTC by Sandy4999

2021-06-16 06:27 UTC, davies commented on docs/en/command_reference.md
> +   dump     dump JuiceFS metadata into a standalone file
`dump metadata into a file`

2021-06-16 06:27 UTC, davies commented on docs/en/command_reference.md
> +   load     load JuiceFS metadata from a previously dumped file
load metadata from a previously dumped JSON file

2021-06-16 06:28 UTC, davies commented on docs/zh_cn/command_reference.md
> +dump JuiceFS metadata into a standalone file
in Chinese

2021-06-16 10:01 UTC, Sandy4999 commented
@xiaogaozi Please take a look at the translated file `docs/zh_cn/command_reference.md`

2021-06-17 01:59 UTC, xiaogaozi requested changes

2021-06-17 01:59 UTC, xiaogaozi commented on docs/zh_cn/command_reference.md
> +RSA私钥的路径 (PEM)
Add space after "RSA"

2021-06-17 01:59 UTC, xiaogaozi commented on docs/zh_cn/command_reference.md
> +使用inode号而不是路径 (当前目录必须在 JuiceFS 挂载点内) (默认: false)
Add space before and after "inode"

2021-06-17 01:59 UTC, xiaogaozi commented on docs/zh_cn/command_reference.md
> +显示JuiceFS的状态。
Add space before and after "JuiceFS"

2021-06-17 01:59 UTC, xiaogaozi commented on docs/zh_cn/command_reference.md
> +将元数据导出到一个JSON文件中。
Add space before and after "JSON"

2021-06-17 01:59 UTC, xiaogaozi commented on docs/zh_cn/command_reference.md
> +从之前导出的JSON文件中加载元数据。
Add space before and after "JSON"

2021-06-17 04:19 UTC, merged