Support all-squash mount option
juicedata/juicefs pull request #5395
Opened 2024-12-18 09:56 UTC by kyungwan-nam

refer to https://github.com/juicedata/juicefs/issues/5394

2024-12-23 03:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/juicedata/juicefs?pullRequest=5395) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/juicedata/juicefs?pullRequest=5395) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/juicedata/juicefs?pullRequest=5395) it.</sub>

2025-01-10 10:04 UTC, jiefenghuang approved these changes

2025-01-10 10:06 UTC, jiefenghuang commented
@kyungwan-nam please sign the cla.

2025-01-17 03:32 UTC, SandyXSD requested changes

2025-01-17 03:32 UTC, SandyXSD commented on cmd/mount_unix.go
> +	nobodyUid, nobodyGid := getNobodyUIDGID()
Do this only when necessary

2025-01-17 03:32 UTC, SandyXSD commented on cmd/mount_unix.go
> +	allSquash := c.String("all-squash")
`DefaultPermission` should be disabled when either squash is specified.

2025-01-17 03:32 UTC, SandyXSD commented on cmd/mount_unix.go
> +		uid, gid := parseUIDGID(allSquash, nobodyUid, nobodyGid)
The uid/gid should never be 0, or it may introduce security vulnerabilities.

2025-01-20 05:43 UTC, kyungwan-nam commented on cmd/mount_unix.go
> +	nobodyUid, nobodyGid := getNobodyUIDGID()
Thanks. I fixed it

2025-01-20 05:50 UTC, kyungwan-nam commented on cmd/mount_unix.go
> +		uid, gid := parseUIDGID(allSquash, nobodyUid, nobodyGid)
I fixed check whether the uid/gid is 0 in ``parseUIDGID``
the uid/gid will be default uid/gid instead of 0 if 0

2025-01-20 05:50 UTC, kyungwan-nam commented on cmd/mount_unix.go
> +	allSquash := c.String("all-squash")
Thanks. I fixed it

2025-01-23 09:17 UTC, SandyXSD approved these changes

2025-01-23 09:17 UTC, merged

2025-01-24 01:54 UTC, kyungwan-nam commented
@SandyXSD @jiefenghuang 
Thank you for working on this!
This feature is very useful for us