update p8s config in doc
juicedata/juicefs pull request #623
Opened 2021-07-10 11:16 UTC by zwwhdls

update p8s config for mount pod which csi driver create.

2021-07-10 11:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/juicedata/juicefs?pullRequest=623) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/juicedata/juicefs?pullRequest=623) before we can accept your contribution.<br/><hr/>**weiwei** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/juicedata/juicefs?pullRequest=623) it.</sub>

2021-07-12 03:25 UTC, xiaogaozi requested changes
The `docs/en/how_to_use_on_kubernetes.md` should be updated also.

2021-07-12 07:23 UTC, zwwhdls commented
@xiaogaozi done

2021-07-12 07:46 UTC, xiaogaozi approved these changes

2021-07-12 07:48 UTC, davies commented
we will wait for the new CSI release.

2021-07-14 08:22 UTC, merged