Go reportcard fix
juicedata/juicefs pull request #86
Opened 2021-01-18 12:12 UTC by last-saiyan

improved `golint` coverage to 60%   [issue](https://github.com/juicedata/juicefs/issues/77)

to test the coverage setup `goreportcard` on local machine and  run `goreportcard-cli`

2021-01-18 14:54 UTC, davies commented on pkg/utils/alloc.go
> +// Alloc allocates memory for page returns slice of byte of lenght `size`
lenght -> length

2021-01-18 14:54 UTC, davies commented on pkg/utils/alloc.go
> +// adds `size` `used` memory
We don't need to add these details in comments

2021-01-18 14:55 UTC, davies commented on pkg/utils/cond.go
> +// returns true incase of timeout else false
incase -> in case

2021-01-18 14:56 UTC, davies commented on pkg/utils/cond.go
> +// Cond struct contains a channel and lock used for synchronization
Cond is similar to sync.Cond, but you can wait without a timeout.

2021-01-18 14:57 UTC, davies commented on pkg/utils/cond.go
> +// Broadcast sends true to channel
Broadcast wake up all the waiters.

2021-01-18 14:57 UTC, davies commented on pkg/utils/cond.go
> +// Signal sends true to the channel
Signal wakes up a waiter.

2021-01-18 14:58 UTC, davies commented on pkg/utils/cond.go
> +// Wait till signal is recieived
Wait until Signal() or Broadcast() is called.

2021-01-18 14:59 UTC, davies commented on pkg/utils/cond.go
> +// WaitWithTimeout waits till timeout or message in signal channel
WaitWithTimeout wait for a signal or a period of `timeout` eclipsed.

2021-01-18 15:00 UTC, davies commented on pkg/utils/cond.go
> +// NewCond creates & returns pointer to new Cond
NewCond creates a Cond.

2021-01-18 15:03 UTC, davies commented on pkg/utils/alloc.go
> +// function is thread safe
Free returns memory to Go heap.

2021-01-18 15:05 UTC, davies commented on pkg/utils/buffer.go
> +// Buffer struct containing slice of byte
Buffer is a buffer to read/write integers.

2021-01-18 15:06 UTC, davies commented on pkg/utils/buffer.go
> +// NewBuffer utility to create *Buffer of given size
NewBuffer returns a buffer with `sz` number of bytes.

2021-01-18 15:20 UTC, davies requested changes
To have a better doc for a function, we should write `the thing it can archive`, not how it is implemented.

2021-01-19 00:08 UTC, suzaku commented
> To have a better doc for a function, we should write `the thing it can archive`, not how it is implemented.

Maybe these kind of doc are better written by the authors 🤦 Other people have to read the code to understand them and tend to write about the implementation.

2021-01-19 11:02 UTC, merged