mount: add `--backup-meta` to periodically backup metadata to object storage
juicedata/juicefs pull request #975
Opened 2021-11-12 08:19 UTC by SandyXSD

2021-11-12 12:38 UTC, davies commented on pkg/vfs/backup.go
> +			last, err = time.Parse("2006-01-02-150405", string(value))
we can use timestamp here

2021-11-12 12:56 UTC, davies requested changes
Unit tests

2021-11-12 12:56 UTC, davies commented on pkg/vfs/backup.go
> +	// Cleanup policy:
Add test cases for these

2021-11-12 12:56 UTC, davies commented on pkg/vfs/backup.go
> +			logger.Infof("backup metadata started")
debug level

2021-11-12 12:56 UTC, davies commented on pkg/vfs/backup.go
> +				logger.Info("backup metadata succeed")
Added the time used by backup.

2021-11-12 16:02 UTC, davies commented on pkg/vfs/backup.go
> +			if iused/5e6 > uint64(interval/time.Hour) {
when interval is less than 1 hour, it will not backup anything

2021-11-15 08:02 UTC, SandyXSD commented on pkg/vfs/backup.go
> +	// Cleanup policy:
7e44334

2021-11-16 14:06 UTC, davies approved these changes

2021-11-16 14:07 UTC, merged